# Generated by Django 6.0.6 on 2026-06-17 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_expand_rbac_roles'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='auditlog',
            name='users_audit_user_id_29b33e_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='users_audit_action_e79129_idx',
        ),
        migrations.RemoveIndex(
            model_name='auditlog',
            name='users_audit_risk_le_2a63e0_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_timestamp',
        ),
        migrations.DeleteModel(
            name='AuditLog',
        ),
    ]
