# Generated by Django 6.0.6 on 2026-06-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_auditlog_users_audit_user_id_29b33e_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
