# Generated by Django 6.0.6 on 2026-06-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('face_enrolled', 'Face Enrolled'), ('face_verified', 'Face Verified'), ('face_failed', 'Face Verification Failed'), ('login', 'Login'), ('logout', 'Logout'), ('suspicious_login', 'Suspicious Login'), ('multiple_face_failures', 'Multiple Face Failures')], max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('risk_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TrustedDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255)),
                ('device_name', models.CharField(blank=True, max_length=100)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('is_trusted', models.BooleanField(default=True)),
            ],
        ),
    ]
